### ISSUE TITLE
Crash on trying to use recursive watcher

### ISSUE THREAD

**Issue by thindil** [onox/inotify-ada#2]
Steps to reproduce:
1. Build examples
2. Run it to monitor root directory:
`bin/monitor /`
3. The program will crash with exception:
`raised CONSTRAINT_ERROR : Inotify.Recursive.Mask_Maps.Insert: attempt to insert key already in map`

Tested with commit 82f7084
If any other information is needed, ask ;)

**Comment by onox** [comment]
Symlinks are no longer followed. Either the link points to a file/folder inside the tree (then it is reachable anyway) or it points to a folder/file outside the tree, which is now no longer allowed.
