### ISSUE TITLE
Event Created cannot be turned off

### ISSUE THREAD

**Issue by bjorn-lundin** [onox/inotify-ada#3]
Hi, 
I'm trying out your binding to Notify, and run the examples on a arm raspberry pi under raspbian.
I set (in the example)
   Instance.Add_Watch
     (Path => Ada.Command_Line.Argument (1),
      Mask => (Closed_Write => True, others => False));
   Instance.Process_Events (Handle_Event'Access);

and still I get events like (changed the output to 1 line per notification)
CREATED /dev/shm/bot/plc ->  [file] '/dev/shm/bot/plc/2021_01_06T15_23_27_558Z_1675.dat'
CLOSED_WRITE /dev/shm/bot/plc ->  [file] '/dev/shm/bot/plc/2021_01_06T15_23_27_558Z_1675.dat'

if I update the file I only get the CLOSED_WRITE but why do I get a CREATED when it is masked out?

And I do got a usage question. Looking at the code I can only see the case where the main goes
into  Instance.Process_Events and stays there, handling the events.
(How do I call Remove_Watch? Only chance is inside Process_Events or in a separate task?)
Is the only way to put this in a separate task if I'd like to monitor (from main) other input sources , like sockets or pipes?

I can work around it but I'd like the thoughts behind the binding
Thanks for a good work :-)

**Comment by bjorn-lundin** [comment]
>I can work around it but I'd like the thoughts behind the binding
I can work around it but I'd like _to know_ the thoughts behind the binding

**Comment by onox** [comment]
Hi, sorry for not noticing this issue early. Apparently I didn't get notified by GitHub.

If I only enable the `Closed_Write` event (on x86-64 with 4.15 kernel), then I only get that event.

1. Which kernel are you using? (`uname -r`)
2. If you rename a file or move the file to outside the watched folder, do you get the `Moved_*` events?
3. Are you using some particular editor?
4. Does the problem also occur if you use a non-recursive instance and watch `/dev/shm/bot/plc`?
5. Can you try to reproduce the problem on an x86-64 machine?

Note that the paths that you watch via a `Recursive_Instance` do have some extra mask bits enabled (`Created`, `Delete_Self`, `Moved_From`, `Moved_To`, and `Moved_Self`), but the original mask is stored in a map and checked against when an event comes in.

Can you provide some exact sequence of steps that you do? Like this:

1. In terminal 1: `mkdir foo`
2. In terminal 2: `alr run --args="path/to/foo"`
3. In terminal 1: some steps here using mkdir/rmdir/touch/rm, etc.

I have only tested calling `Instance.Remove_Watch` before you call `Process_Events`. From within an event handler the following exception may occur:

```
raised CONSTRAINT_ERROR : Inotify.Watch_Maps.Element: no element available because key not in map
```

I noticed though that once you have removed the watch of some subdirectory via a task, you no longer get any events from the root folder that you're watching. So at the moment calling `Remove_Watch` is not recommended from within an event handler.

It would indeed be nice if `Remove_Watch` could be called from within an event handler.

**Comment by onox** [comment]
Removing a watch from within an event handler has been fixed in #4. Procedure `Process_Events` will now no longer block and must be called in a loop. (See the updated example in README.md).

**Comment by onox** [comment]
I'll be closing this issue, but if you can still reproduce the unexpected `Created` event and provide the exact steps to reproduce this on x64, then please reopen the issue or add a comment.

**Comment by bjorn-lundin** [comment]
bnl@pibetbot:/tmp $ uname -a
Linux pibetbot 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux

with the old code I got this (on arm32)

```
with Ada.Command_Line;
with Ada.Text_IO;

with Inotify.Recursive;

procedure Monitor is
   Instance : Inotify.Recursive.Recursive_Instance;

   procedure Handle_Event
     (Subject      : Inotify.Watch;
      Event        : Inotify.Event_Kind;
      Is_Directory : Boolean;
      Name         : String)
   is
      Kind : constant String := (if Is_Directory then "directory" else "file");
   begin
      Ada.Text_IO.Put_Line (Event'Img & " " & Instance.Name (Subject));
      Ada.Text_IO.Put_Line ("  [" & Kind & "] '" & Name & "'");
   end Handle_Event;

   procedure Handle_Move_Event
     (Subject      : Inotify.Watch;
      Is_Directory : Boolean;
      From, To     : String)
   is
      Kind : constant String := (if Is_Directory then "directory" else "file");
   begin
      if From /= "" then
         Ada.Text_IO.Put_Line ("moved " & Kind & " '" & From & "' to '" & To & "'");
      else
         Ada.Text_IO.Put_Line ("moved new " & Kind & " to '" & To & "'");
      end if;
   end Handle_Move_Event;
begin
   Instance.Add_Watch (Path => "/tmp", Mask => (Closed_Write => True, others => False));
   Instance.Process_Events (Handle_Event'Access, Handle_Move_Event'Access);
end Monitor;

```

bnl@pibetbot:/tmp $ touch tst.dat
monitor: CLOSED_WRITE /tmp
  [file] '/tmp/tst.dat'

bnl@pibetbot:/tmp $ mv tst.dat tst.txt
monitor: moved file '/tmp/tst.dat' to '/tmp/tst.txt'

bnl@pibetbot:/tmp $ echo 123 > tst.txt
monitor: CLOSED_WRITE /tmp
  [file] '/tmp/tst.txt'
bnl@pibetbot:/tmp $ rm tst.txt
monitor: nothing



I'll update to our fixes this weekend and test that.
I'll try get it on an Intel as well.
